import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {getStripe} from "@/lib/stripe/server";

export default async function BookingConfirmation({searchParams}:{searchParams:Promise<{session_id?:string;booking_id?:string}>}){
  const q=await searchParams;const supabase=await createClient();const user=supabase?(await supabase.auth.getUser()).data.user:null;if(!user)redirect("/connexion");
  let bookingId=String(q.booking_id??"");let stripePaid=false;
  if(q.session_id){try{const session=await getStripe().checkout.sessions.retrieve(q.session_id);if(session.metadata?.participant_id!==user.id)notFound();bookingId=session.client_reference_id??session.metadata?.booking_id??"";stripePaid=session.payment_status==="paid";}catch{notFound();}}
  if(!/^[0-9a-f-]{36}$/i.test(bookingId))notFound();
  const {data:booking}=await createAdminClient().from("bookings").select("id,participant_id,number_of_people,amount,platform_fee,payment_status,booking_status,trip:trips(id,title,date,start_time,location,organizer:profiles!trips_organizer_id_fkey(first_name,last_name))").eq("id",bookingId).single();if(!booking||booking.participant_id!==user.id)notFound();
  const trip=Array.isArray(booking.trip)?booking.trip[0]:booking.trip;const organizer=trip?(Array.isArray(trip.organizer)?trip.organizer[0]:trip.organizer):null;const confirmed=booking.booking_status==="confirmee"&&booking.payment_status==="paye";const paid=Number(booking.amount)>0;
  return <section className="page-shell confirmation-page"><div className="confirmation-icon">✓</div><span className="eyebrow green">RÉSERVATION {confirmed?"CONFIRMÉE":"REÇUE"}</span><h1>{confirmed||!paid?"Votre réservation est confirmée":"Votre paiement a bien été reçu"}</h1><p>{confirmed||!paid?"Un e-mail de confirmation vient de vous être envoyé.":stripePaid?"Stripe a validé le paiement. NITO finalise votre réservation ; cette page peut être actualisée dans quelques secondes.":"La confirmation du paiement est en cours."}</p><section className="panel-card confirmation-ticket"><h2>{trip?.title}</h2><dl className="summary-list"><div><dt>Date</dt><dd>{trip&&new Intl.DateTimeFormat("fr-FR",{dateStyle:"long"}).format(new Date(trip.date))} à {String(trip?.start_time??"").slice(0,5)}</dd></div><div><dt>Lieu approximatif</dt><dd>{trip?.location}</dd></div><div><dt>Organisateur</dt><dd>{`${organizer?.first_name??""} ${organizer?.last_name??""}`.trim()||"Organisateur NITO"}</dd></div><div><dt>Participants</dt><dd>{booking.number_of_people}</dd></div><div><dt>Montant</dt><dd>{Number(booking.amount)===0?"Gratuit":`${Number(booking.amount).toFixed(2)} €`}<small>Commission NITO incluse : {Number(booking.platform_fee).toFixed(2)} €</small></dd></div><div><dt>Référence</dt><dd><code>{booking.id}</code></dd></div></dl></section><div className="confirmation-actions">{confirmed&&<Link className="primary" href={`/api/bookings/${booking.id}/receipt`} target="_blank">Télécharger le justificatif</Link>}{!confirmed&&paid&&<Link className="primary" href={`/reservation/confirmation?session_id=${encodeURIComponent(q.session_id??"")}`}>Actualiser la confirmation</Link>}<Link className="secondary" href="/reservations">Voir mes réservations</Link>{trip?.id&&<Link className="secondary" href={`/sorties/${trip.id}`}>Voir la sortie</Link>}</div><small>Conservez l’e-mail et la référence de réservation. Le justificatif n’est pas une facture fiscale.</small></section>;
}
