import Image from "next/image";
import Link from "next/link";
import {notFound} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {getTrip} from "@/lib/data";
import {toggleOrganizerSubscription} from "@/app/abonnements/actions";

const fallbackImage="https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=85";

export default async function TripDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{abonnement?:string}>}) {
  const [{id},q]=await Promise.all([params,searchParams]);
  const isUuid=/^[0-9a-f-]{36}$/i.test(id);const supabase=await createClient();
  const remote=isUuid&&supabase?(await supabase.from("trips").select("id,title,description,location,date,start_time,duration,difficulty,maximum_participants,price,status,activity:activities(name),organizer:profiles(id,first_name,last_name,average_rating)").eq("id",id).single()).data:null;
  if(remote){
    const activity=Array.isArray(remote.activity)?remote.activity[0]:remote.activity;const organizer=Array.isArray(remote.organizer)?remote.organizer[0]:remote.organizer;
    const {count}=await supabase!.from("bookings").select("number_of_people",{count:"exact",head:true}).eq("trip_id",remote.id).eq("booking_status","confirmee");
    const user=(await supabase!.auth.getUser()).data.user;
    const viewer=user?(await supabase!.from("profiles").select("user_type").eq("id",user.id).single()).data:null;
    const subscription=user&&organizer?.id&&viewer?.user_type==="participant"?(await supabase!.from("organizer_subscriptions").select("organizer_id").eq("participant_id",user.id).eq("organizer_id",organizer.id).maybeSingle()).data:null;
    return <section className="page-shell">{q.abonnement==="suivi"&&<p className="form-alert success">Vous suivez maintenant cet organisateur.</p>}{q.abonnement==="retire"&&<p className="form-alert success">L’organisateur a été retiré de vos abonnements.</p>}{q.abonnement==="erreur"&&<p className="form-alert error">L’abonnement n’a pas pu être modifié.</p>}<div className="detail-cover"><Image src={fallbackImage} alt={remote.title} fill priority sizes="100vw"/><div className="detail-title"><span className="eyebrow">{activity?.name??"Sortie nature"}</span><h1>{remote.title}</h1></div></div><div className="detail-grid"><div><section className="panel-card"><h2>À propos de cette sortie</h2><p>{remote.description}</p></section><section className="panel-card"><h3>Votre organisateur</h3><p><strong>{organizer?.first_name} {organizer?.last_name}</strong> · ★ {Number(organizer?.average_rating??0).toFixed(1)}</p>{organizer?.id&&viewer?.user_type==="participant"?<form action={toggleOrganizerSubscription}><input type="hidden" name="organizer_id" value={organizer.id}/><input type="hidden" name="trip_id" value={remote.id}/><button className={subscription?"secondary":"primary"} name="operation" value={subscription?"ne_plus_suivre":"suivre"}>{subscription?"Ne plus suivre":"Suivre cet organisateur"}</button></form>:!user?<Link className="secondary" href={`/connexion?next=/sorties/${remote.id}`}>Connectez-vous pour suivre cet organisateur</Link>:null}</section></div><aside className="panel-card booking-card"><span className="big-price">{Number(remote.price).toFixed(2)} €</span> par personne<p>{remote.date} à {String(remote.start_time).slice(0,5)}</p><p>{remote.location} · {remote.duration} min</p><p>{Math.max(0,remote.maximum_participants-(count??0))} places disponibles</p><form action="/api/create-checkout-session" method="post"><input type="hidden" name="tripId" value={remote.id}/><label>Participants<input name="quantity" type="number" min="1" max="20" defaultValue="1"/></label><label className="legal-consent"><input type="checkbox" name="booking_terms" value="accepted" required/><span>J’accepte les <Link href="/conditions" target="_blank">conditions de réservation</Link> et la <Link href="/annulations" target="_blank">politique d’annulation</Link>.</span></label><button className="primary wide">Réserver et payer</button></form><small className="payment-disclaimer">Paiement sécurisé par Stripe · Commission NITO de 10 % incluse</small></aside></div></section>;
  }
  const trip=getTrip(id);if(!trip)notFound();
  return <section className="page-shell"><div className="detail-cover"><Image src={trip.image} alt={trip.title} fill priority sizes="100vw"/><div className="detail-title"><span className="eyebrow">{trip.activity}</span><h1>{trip.title}</h1></div></div><div className="detail-grid"><section className="panel-card"><h2>À propos de cette sortie</h2><p>{trip.description}</p></section><aside className="panel-card booking-card"><span className="big-price">{trip.price} €</span><p>Cette sortie de démonstration n’est pas réservable. Publiez une sortie depuis l’espace organisateur pour tester Stripe Connect.</p><button className="secondary wide" disabled>Réservation indisponible</button></aside></div></section>;
}
