import Image from "next/image";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getTrip } from "@/lib/data";
const fallbackImage="https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=85";
export default async function TripDetail({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const isUuid=/^[0-9a-f-]{36}$/i.test(id);const supabase=await createClient();
  const remote=isUuid&&supabase?(await supabase.from("trips").select("id,title,description,location,date,start_time,duration,difficulty,maximum_participants,price,status,activity:activities(name),organizer:profiles(first_name,last_name,average_rating)").eq("id",id).single()).data:null;
  if(remote){const activity=Array.isArray(remote.activity)?remote.activity[0]:remote.activity;const organizer=Array.isArray(remote.organizer)?remote.organizer[0]:remote.organizer;const {count}=await supabase!.from("bookings").select("number_of_people",{count:"exact",head:true}).eq("trip_id",remote.id).eq("booking_status","confirmee");return <section className="page-shell"><div className="detail-cover"><Image src={fallbackImage} alt={remote.title} fill priority sizes="100vw"/><div className="detail-title"><span className="eyebrow">{activity?.name??"Sortie nature"}</span><h1>{remote.title}</h1></div></div><div className="detail-grid"><div><section className="panel-card"><h2>À propos de cette sortie</h2><p>{remote.description}</p></section><section className="panel-card"><h3>Votre guide</h3><p><strong>{organizer?.first_name} {organizer?.last_name}</strong> · ★ {Number(organizer?.average_rating??0).toFixed(1)}</p></section></div><aside className="panel-card booking-card"><span className="big-price">{Number(remote.price).toFixed(2)} €</span> par personne<p>{remote.date} à {String(remote.start_time).slice(0,5)}</p><p>{remote.location} · {remote.duration} min</p><p>{Math.max(0,remote.maximum_participants-(count??0))} places disponibles</p><form action="/api/create-checkout-session" method="post"><input type="hidden" name="tripId" value={remote.id}/><label>Participants<input name="quantity" type="number" min="1" max="20" defaultValue="1"/></label><button className="primary wide">Réserver et payer</button></form><small className="payment-disclaimer">Paiement sécurisé par Stripe · Commission NaturEnsemble incluse</small></aside></div></section>}
  const trip=getTrip(id);if(!trip)notFound();return <section className="page-shell"><div className="detail-cover"><Image src={trip.image} alt={trip.title} fill priority sizes="100vw"/><div className="detail-title"><span className="eyebrow">{trip.activity}</span><h1>{trip.title}</h1></div></div><div className="detail-grid"><section className="panel-card"><h2>À propos de cette sortie</h2><p>{trip.description}</p></section><aside className="panel-card booking-card"><span className="big-price">{trip.price} €</span><p>Cette sortie de démonstration n’est pas réservable. Publiez une sortie depuis l’espace organisateur pour tester Stripe Connect.</p><button className="secondary wide" disabled>Réservation indisponible</button></aside></div></section>;
}
