import { createClient } from "@/lib/supabase/server";
import { completeOnboarding } from "./actions";

export const metadata={title:"Profil organisateur"};

export default async function OrganizerOnboarding({searchParams}:{searchParams:Promise<{erreur?:string;stripe?:string;identite?:string}>}){
  const q=await searchParams;const supabase=await createClient();
  const activities=supabase?((await supabase.from("activities").select("id,name,icon").order("name")).data??[]):[];
  const user=supabase?(await supabase.auth.getUser()).data.user:null;
  const profile=user&&supabase?(await supabase.from("profiles").select("identity_verified").eq("id",user.id).single()).data:null;
  const identity=user&&supabase?(await supabase.from("identity_checks").select("status").eq("user_id",user.id).eq("provider","stripe_identity").order("created_at",{ascending:false}).limit(1).maybeSingle()).data:null;
  return <section className="page-shell narrow"><div className="form-intro"><span className="eyebrow green">DEVENIR ORGANISATEUR</span><h1>Présentez votre expérience</h1><p>Ces informations permettront à l’équipe de vérifier votre profil et de rassurer les participants.</p></div>
    <form className="big-form" action={completeOnboarding}>{q.erreur&&<p className="form-alert error">Le formulaire n’a pas pu être enregistré.</p>}<h2>Votre profil</h2><label>Niveau d’organisateur<select name="organizer_level" required defaultValue="passionne_verifie"><option value="passionne_verifie">Passionné vérifié</option><option value="association">Association</option><option value="professionnel_diplome">Professionnel diplômé</option><option value="guide_educateur_sportif">Guide ou éducateur sportif</option></select></label><label>Structure ou affiliation éventuelle<input name="affiliation_name" placeholder="Association, club, entreprise…"/></label><p className="secure-note">Le niveau déclaré détermine les sorties autorisées. L’encadrement sportif rémunéré est réservé aux professionnels dont la qualification et l’assurance ont été vérifiées.</p><label>Ville<input name="city" required/></label><label>Biographie<textarea name="bio" rows={6} minLength={40} required/></label><label>Compétences<input name="skills" placeholder="Animation, premiers secours, faune…"/></label><fieldset className="activity-checks"><legend>Activités maîtrisées</legend>{activities.map(a=><label key={a.id}><input type="checkbox" name="activities" value={a.id}/><span>{a.icon} {a.name}</span></label>)}</fieldset><h2>Assurance</h2><div className="two-cols"><label>Assureur<input name="insurance_provider"/></label><label>Numéro de police<input name="insurance_policy_number"/></label></div><label>Date d’expiration<input name="insurance_expires_at" type="date"/></label><button className="primary wide">Enregistrer mon dossier</button></form>
    <section className="panel-card connect-card"><span className="eyebrow green">VERSEMENTS SÉCURISÉS</span><h2>Compte Stripe Connect</h2>{q.stripe==="active"?<p className="form-alert success">Votre compte Stripe est actif et peut recevoir des paiements.</p>:q.stripe==="incomplet"?<p className="form-alert error">Stripe demande encore quelques informations.</p>:q.stripe==="plateforme-incomplete"?<p className="form-alert error">La configuration Connect de NITO doit encore être confirmée dans Stripe avant de pouvoir créer un compte organisateur en production.</p>:q.stripe==="erreur"?<p className="form-alert error">Stripe n’a pas pu démarrer la configuration des versements. Réessayez dans quelques instants.</p>:<p>Stripe collecte et vérifie directement votre identité et vos coordonnées bancaires. NITO ne les conserve jamais.</p>}<form action="/api/create-connect-account" method="post"><button className="primary">{q.stripe?"Réessayer la configuration Stripe":"Configurer mes versements"}</button></form></section>
    <section className="panel-card connect-card"><span className="eyebrow green">IDENTITÉ SÉCURISÉE</span><h2>Vérification d’identité</h2>{profile?.identity_verified||identity?.status==="verifie"?<p className="form-alert success">✓ Identité vérifiée</p>:identity?.status==="en_attente"||q.identite==="traitement"?<p className="form-alert success">Vos informations sont en cours de vérification par Stripe.</p>:q.identite==="a_reprendre"||identity?.status==="rejete"?<p className="form-alert error">La vérification doit être reprise. Stripe vous indiquera le document à corriger.</p>:q.identite==="erreur"?<p className="form-alert error">Impossible de démarrer la vérification pour le moment.</p>:<p>Stripe vérifiera votre pièce d’identité et comparera votre visage avec un selfie. NaturEnsemble ne reçoit et ne conserve aucune image.</p>}{!profile?.identity_verified&&<form action="/api/identity/create-session" method="post"><button className="primary">{identity?"Reprendre la vérification":"Vérifier mon identité"}</button></form>}</section>
    <section className="panel-card connect-card"><span className="eyebrow green">DOCUMENTS PRIVÉS</span><h2>Justificatifs organisateur</h2><p>Ces fichiers restent privés. Seuls vous et les administrateurs autorisés pouvez obtenir un lien temporaire. Les documents demandés dépendent du niveau et de l’activité déclarés.</p><div className="two-cols"><DocumentUpload bucket="insurance-documents" type="assurance_rc_pro" label="Assurance responsabilité civile professionnelle"/><DocumentUpload bucket="professional-documents" type="diplome" label="Diplôme ou titre professionnel"/><DocumentUpload bucket="professional-documents" type="carte_professionnelle" label="Carte professionnelle"/><DocumentUpload bucket="professional-documents" type="affiliation_structure" label="Affiliation à une structure"/></div></section>
  </section>;
}

function DocumentUpload({bucket,type,label}:{bucket:string;type:string;label:string}){return <form action="/api/storage/upload" method="post" encType="multipart/form-data"><input type="hidden" name="bucket" value={bucket}/><input type="hidden" name="document_type" value={type}/><input type="hidden" name="redirect" value="/organisateur/onboarding"/><label>{label}<input type="file" name="file" accept="application/pdf,image/jpeg,image/png" required/></label><button className="secondary">Envoyer</button></form>}
