import Link from "next/link";
import {redirect} from "next/navigation";
import {DashboardNav} from "@/components/dashboard-nav";
import {createClient} from "@/lib/supabase/server";

export const metadata={title:"Espace organisateur"};

export default async function Organizer(){
  const supabase=await createClient();if(!supabase)return null;const user=(await supabase.auth.getUser()).data.user;if(!user)redirect("/connexion");const today=new Date().toISOString().slice(0,10);
  const [{count:active},{count:followers},{data:trips},{data:reviews},{data:ownedTrips},{data:organizer},{count:pendingDocuments},{count:unreadAlerts}]=await Promise.all([
    supabase.from("trips").select("id",{count:"exact",head:true}).eq("organizer_id",user.id).eq("status","publiee").gte("date",today),
    supabase.from("organizer_subscriptions").select("participant_id",{count:"exact",head:true}).eq("organizer_id",user.id),
    supabase.from("trips").select("id,title,date,start_time,location,status").eq("organizer_id",user.id).in("status",["brouillon","en_attente","publiee"]).gte("date",today).order("date").limit(10),
    supabase.from("reviews").select("rating").eq("recipient_id",user.id).eq("moderation_status","publie"),
    supabase.from("trips").select("id").eq("organizer_id",user.id),
    supabase.from("organizer_profiles").select("onboarding_status,stripe_charges_enabled,stripe_payouts_enabled,qualification_verified,insurance_verified,stripe_requirements_currently_due").eq("organizer_id",user.id).maybeSingle(),
    supabase.from("organizer_documents").select("id",{count:"exact",head:true}).eq("organizer_id",user.id).eq("status","en_attente"),
    supabase.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",user.id).is("read_at",null),
  ]);
  const tripIds=(ownedTrips??[]).map(trip=>trip.id);const [{data:bookings},{data:payouts}]=await Promise.all([
    tripIds.length?supabase.from("bookings").select("trip_id,number_of_people,amount,platform_fee,payment_status,booking_status").in("trip_id",tripIds):Promise.resolve({data:[]}),
    supabase.from("payouts").select("amount,status,created_at").eq("organizer_id",user.id).order("created_at",{ascending:false}).limit(5),
  ]);
  const confirmed=(bookings??[]).filter(booking=>["confirmee","terminee"].includes(booking.booking_status));const participants=confirmed.reduce((sum,item)=>sum+item.number_of_people,0);const paid=(bookings??[]).filter(item=>item.payment_status==="paye");const revenue=paid.reduce((sum,item)=>sum+Number(item.amount)-Number(item.platform_fee),0);const failedPayments=(bookings??[]).filter(item=>item.payment_status==="echoue").length;const ratings=reviews??[];const rating=ratings.length?ratings.reduce((sum,item)=>sum+Number(item.rating),0)/ratings.length:0;const payoutsTotal=(payouts??[]).filter(item=>item.status==="paye").reduce((sum,item)=>sum+Number(item.amount),0);
  const alerts=[...(!organizer?.stripe_charges_enabled||!organizer?.stripe_payouts_enabled?[{kind:"warning",text:"Votre compte de versement Stripe nécessite une action.",href:"/organisateur/onboarding",action:"Ouvrir mon dossier"}]:[]),...(organizer?.stripe_requirements_currently_due?.length?[{kind:"warning",text:`Stripe demande ${organizer.stripe_requirements_currently_due.length} information(s) complémentaire(s).`,href:"/organisateur/onboarding",action:"Compléter"}]:[]),...(pendingDocuments?[{kind:"info",text:`${pendingDocuments} document(s) en cours de vérification par NITO.`,href:"/organisateur/onboarding",action:"Voir les documents"}]:[]),...(failedPayments?[{kind:"danger",text:`${failedPayments} paiement(s) non abouti(s) sur vos sorties.`,href:"/organisateur",action:"Consulter"}]:[]),...(unreadAlerts?[{kind:"info",text:`${unreadAlerts} notification(s) non lue(s).`,href:"/notifications",action:"Lire"}]:[])];
  const shortcuts=[{icon:"🗓️",title:"Sorties à gérer",value:trips?.length??0,text:"Modifier, fermer, annuler ou consulter une sortie.",href:"#sorties"},{icon:"👥",title:"Participants",value:participants,text:"Les listes détaillées se trouvent dans chaque sortie.",href:trips?.[0]?`/organisateur/sorties/${trips[0].id}`:"/organisateur/sorties/nouvelle"},{icon:"💶",title:"Revenus et versements",value:`${revenue.toFixed(2)} €`,text:`${payoutsTotal.toFixed(2)} € versés par Stripe.`,href:"/organisateur/onboarding"},{icon:"📄",title:"Documents",value:pendingDocuments??0,text:"Identité, qualification et assurance.",href:"/organisateur/onboarding"}];
  return <section className="page-shell role-dashboard"><DashboardNav role="organizer"/><div className="page-header"><div><span className="eyebrow green">ESPACE ORGANISATEUR</span><h1>Pilotez vos sorties</h1><p>Participants, revenus, documents et alertes importantes.</p></div><Link className="primary" href="/organisateur/sorties/nouvelle">Créer une sortie</Link></div>{alerts.length>0&&<section className="dashboard-alerts"><h2>À traiter</h2>{alerts.map((alert,index)=><Link className={`dashboard-alert ${alert.kind}`} href={alert.href} key={`${alert.text}-${index}`}><b>{alert.text}</b><span>{alert.action} →</span></Link>)}</section>}<div className="role-action-grid organizer-actions">{shortcuts.map(item=><Link className="role-action-card" href={item.href} key={item.title}><span className="role-action-icon">{item.icon}</span><div><span>{item.title}</span><strong>{item.value}</strong><p>{item.text}</p><b>Ouvrir →</b></div></Link>)}</div><div className="admin-kpis"><div><span>Sorties actives</span><strong>{active??0}</strong></div><div><span>Participants confirmés</span><strong>{participants}</strong></div><div><span>Revenus nets</span><strong>{revenue.toFixed(2)} €</strong></div><div><span>Note moyenne</span><strong>{rating.toFixed(1)}/5</strong></div><div><span>Abonnés</span><strong>{followers??0}</strong></div></div><section className="panel-card" id="sorties"><div className="section-heading-compact"><h2>Vos prochaines sorties</h2><Link className="text-link" href="/organisateur/sorties/nouvelle">Nouvelle sortie</Link></div>{!trips?.length?<div className="empty-state"><p>Aucune sortie programmée.</p><Link className="primary" href="/organisateur/sorties/nouvelle">Créer ma première sortie</Link></div>:trips.map(trip=><div className="admin-row" key={trip.id}><span><Link className="text-link" href={`/sorties/${trip.id}`}>{trip.title}</Link><small>{new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium"}).format(new Date(trip.date))} à {String(trip.start_time).slice(0,5)} · {trip.location} · {trip.status}</small></span><Link className="secondary" href={`/organisateur/sorties/${trip.id}`}>Gérer et voir les participants</Link></div>)}</section></section>;
}
