import Stripe from "stripe";
import {createAdminClient} from "@/lib/supabase/admin";
import {getStripe} from "@/lib/stripe/server";
import {getBookingEmailContext,sendTransactionalEmail} from "@/lib/email/server";
import {stripeRequirementsDigest,StripeConnectSnapshot} from "@/lib/domain/stripe-connect";
export const runtime="nodejs";

async function emailPaymentFailure(bookingId:string){const context=await getBookingEmailContext(bookingId);if(context?.participant?.email&&context.trip)await sendTransactionalEmail({eventKey:`payment-failed:${bookingId}`,to:context.participant.email,userId:context.participant_id,template:"payment_failed",subject:`Paiement non abouti : ${context.trip.title}`,heading:"Votre paiement n’a pas abouti",content:`Votre réservation pour ${context.trip.title} n’a pas été confirmée. Vous pouvez réessayer avec un autre moyen de paiement.`,actionLabel:"Réessayer",actionUrl:`${process.env.NEXT_PUBLIC_SITE_URL}/sorties/${context.trip.id}`})}

export async function POST(request:Request){
  const webhookSecrets=[process.env.STRIPE_WEBHOOK_SECRET,process.env.STRIPE_CONNECT_WEBHOOK_SECRET].filter((secret):secret is string=>Boolean(secret));
  const signature=request.headers.get("stripe-signature");if(!webhookSecrets.length)return new Response("Webhook Stripe non configuré",{status:503});if(!signature)return new Response("Signature absente",{status:400});
  const payload=await request.text();let event:Stripe.Event|undefined;for(const secret of webhookSecrets){try{event=getStripe().webhooks.constructEvent(payload,signature,secret);break}catch{}}
  if(!event)return new Response("Signature invalide",{status:400});
  const admin=createAdminClient();const {error:claimError}=await admin.from("stripe_events").insert({stripe_event_id:event.id,event_type:event.type,livemode:event.livemode,connected_account_id:event.account??null});
  if(claimError?.code==="23505")return new Response("Déjà traité");if(claimError)return new Response("Journal indisponible",{status:500});
  try{
    switch(event.type){
      case "checkout.session.completed":case "checkout.session.async_payment_succeeded":{
        const session=event.data.object as Stripe.Checkout.Session;if(session.payment_status!=="paid")break;const bookingId=session.client_reference_id??session.metadata?.booking_id;if(!bookingId)throw new Error("Réservation absente");
        const paymentIntentId=typeof session.payment_intent==="string"?session.payment_intent:session.payment_intent?.id;if(!paymentIntentId)throw new Error("PaymentIntent absent");
        const intent=await getStripe().paymentIntents.retrieve(paymentIntentId,{expand:["latest_charge"]});const charge=typeof intent.latest_charge==="object"?intent.latest_charge:null;
        await admin.from("bookings").update({payment_status:"paye",booking_status:"confirmee",stripe_payment_intent_id:intent.id,stripe_charge_id:charge?.id??null,stripe_transfer_id:charge&&typeof charge.transfer==="string"?charge.transfer:null,stripe_application_fee_id:charge&&typeof charge.application_fee==="string"?charge.application_fee:null,payment_failure_reason:null}).eq("id",bookingId);
        const context=await getBookingEmailContext(bookingId);
        if(context?.participant?.email&&context.trip)await sendTransactionalEmail({eventKey:`booking-confirmed:${bookingId}`,to:context.participant.email,userId:context.participant_id,template:"booking_confirmed",subject:`Réservation confirmée : ${context.trip.title}`,heading:"Votre réservation est confirmée",content:`Bonjour ${context.participant.first_name||""},\nVotre réservation de ${context.number_of_people} place(s) pour ${context.trip.title} est confirmée. Montant payé : ${Number(context.amount).toFixed(2)} €.`,actionLabel:"Voir mon calendrier",actionUrl:`${process.env.NEXT_PUBLIC_SITE_URL}/calendrier`});
        if(context?.organizer?.email&&context.trip)await sendTransactionalEmail({eventKey:`organizer-new-booking:${bookingId}`,to:context.organizer.email,userId:context.trip.organizer_id,template:"organizer_new_booking",subject:`Nouvelle réservation : ${context.trip.title}`,heading:"Vous avez une nouvelle réservation",content:`${context.participant?.first_name||"Un participant"} a réservé ${context.number_of_people} place(s) pour ${context.trip.title}.`,actionLabel:"Ouvrir mon tableau de bord",actionUrl:`${process.env.NEXT_PUBLIC_SITE_URL}/organisateur`});break;
      }
      case "checkout.session.async_payment_failed":case "checkout.session.expired":{const session=event.data.object as Stripe.Checkout.Session;const bookingId=session.client_reference_id??session.metadata?.booking_id;if(bookingId){await admin.from("bookings").update({payment_status:"echoue",booking_status:"annulee",payment_failure_reason:event.type,cancelled_at:new Date().toISOString()}).eq("id",bookingId);await emailPaymentFailure(bookingId)}break;}
      case "payment_intent.payment_failed":{const intent=event.data.object as Stripe.PaymentIntent;const {data:failed}=await admin.from("bookings").update({payment_status:"echoue",payment_failure_reason:intent.last_payment_error?.message??"Paiement refusé"}).eq("stripe_payment_intent_id",intent.id).select("id").single();if(failed)await emailPaymentFailure(failed.id);break;}
      case "charge.refunded":{const charge=event.data.object as Stripe.Charge;if(charge.refunded){const {data:refunded}=await admin.from("bookings").update({payment_status:"rembourse",booking_status:"annulee"}).eq("stripe_charge_id",charge.id).select("id").single();if(refunded){const context=await getBookingEmailContext(refunded.id);if(context?.participant?.email&&context.trip)await sendTransactionalEmail({eventKey:`booking-refunded:${refunded.id}`,to:context.participant.email,userId:context.participant_id,template:"booking_refunded",subject:`Remboursement confirmé : ${context.trip.title}`,heading:"Votre réservation a été remboursée",content:`Le remboursement de ${Number(context.amount).toFixed(2)} € pour ${context.trip.title} a été confirmé. Le délai d’apparition dépend de votre banque.`,actionLabel:"Voir mon calendrier",actionUrl:`${process.env.NEXT_PUBLIC_SITE_URL}/calendrier`})}}break;}
      case "refund.updated":case "refund.created":{const refund=event.data.object as Stripe.Refund;const mapped=refund.status==="succeeded"?"rembourse":refund.status==="failed"||refund.status==="canceled"?"echoue":"en_attente";await admin.from("refunds").update({status:mapped}).eq("stripe_refund_id",refund.id);break;}
      case "charge.dispute.created":case "charge.dispute.updated":case "charge.dispute.closed":{const dispute=event.data.object as Stripe.Dispute;const chargeId=typeof dispute.charge==="string"?dispute.charge:dispute.charge.id;const {data:booking}=await admin.from("bookings").select("id").eq("stripe_charge_id",chargeId).single();await admin.from("payment_disputes").upsert({booking_id:booking?.id??null,stripe_dispute_id:dispute.id,stripe_charge_id:chargeId,amount:dispute.amount/100,currency:dispute.currency,reason:dispute.reason,status:dispute.status,evidence_due_at:dispute.evidence_details?.due_by?new Date(dispute.evidence_details.due_by*1000).toISOString():null},{onConflict:"stripe_dispute_id"});break;}
      case "account.updated":{const account=event.data.object as Stripe.Account;const current=account.requirements?.currently_due??[];const snapshot:StripeConnectSnapshot={chargesEnabled:Boolean(account.charges_enabled),payoutsEnabled:Boolean(account.payouts_enabled),detailsSubmitted:Boolean(account.details_submitted),currentlyDue:current,eventuallyDue:account.requirements?.eventually_due??[],disabledReason:account.requirements?.disabled_reason??null,currentDeadline:account.requirements?.current_deadline??null};const digest=stripeRequirementsDigest(snapshot);const {data:organizer}=await admin.from("organizer_profiles").select("organizer_id,stripe_requirements_digest").eq("stripe_connect_account_id",account.id).maybeSingle();await admin.from("organizer_profiles").update({stripe_charges_enabled:snapshot.chargesEnabled,stripe_payouts_enabled:snapshot.payoutsEnabled,stripe_details_submitted:snapshot.detailsSubmitted,stripe_requirements_currently_due:snapshot.currentlyDue,stripe_requirements_eventually_due:snapshot.eventuallyDue,stripe_disabled_reason:snapshot.disabledReason,stripe_requirements_deadline:snapshot.currentDeadline?new Date(snapshot.currentDeadline*1000).toISOString():null,stripe_requirements_digest:digest}).eq("stripe_connect_account_id",account.id);if(organizer&&current.length&&organizer.stripe_requirements_digest!==digest)await admin.from("notifications").insert({user_id:organizer.organizer_id,type:"stripe_action_required",title:"Action requise sur votre compte Stripe",content:"Stripe demande de nouvelles informations pour maintenir les paiements ou les versements actifs.",data:{url:"/organisateur/onboarding"}});break;}
      case "identity.verification_session.processing":case "identity.verification_session.requires_input":case "identity.verification_session.verified":case "identity.verification_session.canceled":{const session=event.data.object as Stripe.Identity.VerificationSession;const userId=session.metadata.naturensemble_user_id||session.client_reference_id;const status=session.status==="verified"?"verifie":session.status==="processing"?"en_attente":session.last_error?"rejete":"non_soumis";await admin.from("identity_checks").update({status,submitted_at:session.status!=="requires_input"?new Date().toISOString():null,verified_at:session.status==="verified"?new Date().toISOString():null,last_error_code:session.last_error?.code??null}).eq("provider_check_id",session.id);if(userId)await admin.from("profiles").update({identity_verified:session.status==="verified"}).eq("id",userId);break;}
      case "payout.created":case "payout.updated":case "payout.paid":case "payout.failed":{const payout=event.data.object as Stripe.Payout;if(!event.account)break;const {data:organizer}=await admin.from("organizer_profiles").select("organizer_id").eq("stripe_connect_account_id",event.account).single();if(!organizer)break;const status=payout.status==="paid"?"paye":payout.status==="failed"||payout.status==="canceled"?"echoue":payout.status==="pending"?"en_attente":"en_cours";await admin.from("payouts").upsert({organizer_id:organizer.organizer_id,stripe_payout_id:payout.id,amount:payout.amount/100,status,paid_at:payout.status==="paid"?new Date().toISOString():null},{onConflict:"stripe_payout_id"});break;}
    }
    await admin.from("stripe_events").update({processed_at:new Date().toISOString()}).eq("stripe_event_id",event.id);return new Response("ok");
  }catch(error){console.error("Stripe webhook",event.id,event.type,error);await admin.from("stripe_events").delete().eq("stripe_event_id",event.id);return new Response("Traitement échoué",{status:500})}
}
