import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {validAttachment} from "@/lib/domain/rules";

export async function POST(request:Request){
  const supabase=await createClient();if(!supabase)return NextResponse.json({error:"Supabase non configuré"},{status:503});const user=(await supabase.auth.getUser()).data.user;if(!user)return NextResponse.json({error:"Non authentifié"},{status:401});
  const form=await request.formData();const tripId=String(form.get("trip_id")??"");const text=String(form.get("content")??"").trim();const file=form.get("file");if(!/^[0-9a-f-]{36}$/i.test(tripId)||!text||text.length>4000)return NextResponse.json({error:"Message invalide"},{status:400});if(file instanceof File&&file.size>0&&!validAttachment(file))return NextResponse.json({error:"Pièce jointe invalide"},{status:400});
  const admin=createAdminClient();let uploadedPath:string|null=null;if(file instanceof File&&file.size>0){const ext=file.type==="application/pdf"?"pdf":file.type==="image/jpeg"?"jpg":file.type==="image/png"?"png":"webp";uploadedPath=`${user.id}/group-${tripId}/${crypto.randomUUID()}.${ext}`;const {error}=await admin.storage.from("message-attachments").upload(uploadedPath,new Uint8Array(await file.arrayBuffer()),{contentType:file.type});if(error)return NextResponse.json({error:"La pièce jointe n’a pas pu être envoyée"},{status:500});}
  const {data,error}=await supabase.from("trip_group_messages").insert({trip_id:tripId,sender_id:user.id,content:text}).select("id,trip_id,sender_id,content,created_at").single();if(error){if(uploadedPath)await admin.storage.from("message-attachments").remove([uploadedPath]);return NextResponse.json({error:"Vous ne pouvez pas écrire dans ce groupe"},{status:403});}
  let attachment=null;if(file instanceof File&&file.size>0&&uploadedPath){const result=await supabase.from("trip_group_message_attachments").insert({message_id:data.id,storage_path:uploadedPath,original_name:file.name,mime_type:file.type,size_bytes:file.size}).select("id,original_name,mime_type").single();if(result.error){await admin.storage.from("message-attachments").remove([uploadedPath]);await admin.from("trip_group_messages").delete().eq("id",data.id);return NextResponse.json({error:"La pièce jointe n’a pas pu être enregistrée"},{status:500});}attachment=result.data;}
  return NextResponse.json({...data,attachment});
}

export async function PATCH(request:Request){const supabase=await createClient();if(!supabase)return NextResponse.json({error:"Supabase non configuré"},{status:503});const user=(await supabase.auth.getUser()).data.user;if(!user)return NextResponse.json({error:"Non authentifié"},{status:401});const {trip_id}=await request.json();if(!/^[0-9a-f-]{36}$/i.test(String(trip_id)))return NextResponse.json({error:"Groupe invalide"},{status:400});const readAt=new Date().toISOString();const {error}=await supabase.from("trip_group_members").update({last_read_at:readAt}).eq("trip_id",trip_id).eq("user_id",user.id);if(!error)await supabase.from("notifications").update({read_at:readAt}).eq("user_id",user.id).eq("type","nouveau_message_groupe").contains("data",{trip_id});return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({ok:true,read_at:readAt});}
