import Link from "next/link";
import type {Metadata} from "next";
import {TripCard} from "@/components/trip-card";
import {createClient} from "@/lib/supabase/server";
import {toTripCard} from "@/lib/trip-display";

export const metadata:Metadata={title:"NITO — Sorties et activités nature",description:"Découvrez et réservez des sorties nature guidées par des passionnés près de chez vous.",alternates:{canonical:"/"}};

export default async function Home(){
  const supabase=await createClient();
  const today=new Date().toISOString().slice(0,10);
  const user=supabase?(await supabase.auth.getUser()).data.user:null;
  const [profileResult,activitiesResult,tripsResult,membersResult,tripsCountResult,reviewsResult]=supabase?await Promise.all([
    user?supabase.from("profiles").select("user_type").eq("id",user.id).single():Promise.resolve({data:null}),
    supabase.from("activities").select("id,name,icon").order("name"),
    supabase.from("trips").select("id,title,location,date,price,activity:activities(name),organizer:profiles(first_name,last_name,average_rating),images:trip_images(public_url,alt_text,position)").eq("status","publiee").gte("date",today).order("date").limit(3),
    supabase.from("profiles").select("id",{count:"exact",head:true}),
    supabase.from("trips").select("id",{count:"exact",head:true}).eq("status","publiee"),
    supabase.from("reviews").select("rating"),
  ]):[{data:null},{data:[]},{data:[]},{count:0},{count:0},{data:[]}];
  const profile=profileResult.data;const activities=activitiesResult.data??[];const trips=(tripsResult.data??[]).map(row=>toTripCard(row));const ratings=reviewsResult.data??[];const averageRating=ratings.length?ratings.reduce((sum,item)=>sum+Number(item.rating),0)/ratings.length:0;const canOrganize=profile?.user_type==="organisateur"||profile?.user_type==="administrateur";
  return <><section className="hero"><div className="hero-overlay"/><div className="hero-content"><span className="eyebrow">RENCONTREZ · APPRENEZ · RESPIREZ</span><h1>La nature se partage<br/>mieux ensemble.</h1><p>Découvrez des sorties guidées par des passionnés, près de chez vous.</p><form className="search-bar" action="/explorer"><label><span>Activité</span><select name="activite"><option value="">Toutes</option>{activities.map(activity=><option key={activity.id} value={activity.name}>{activity.name}</option>)}</select></label><label><span>Lieu</span><input name="lieu" placeholder="Votre région"/></label><label><span>Date</span><input name="date" type="date"/></label><button className="primary">Rechercher</button></form><div className="trust-line"><span>✓ Profils vérifiés</span><span>✓ Paiement sécurisé</span><span>✓ Avis authentiques</span></div></div></section><section className="section-wrap"><div className="section-title-row"><div><span className="eyebrow green">PROCHAINEMENT</span><h2>Sorties à découvrir</h2></div><Link className="text-link" href="/explorer">Voir toutes les sorties →</Link></div>{trips.length?<div className="card-grid">{trips.map(trip=><TripCard key={trip.id} trip={trip}/>)}</div>:<div className="empty-state"><h3>Les premières sorties arrivent bientôt</h3><p>Les propositions validées par NITO apparaîtront ici.</p></div>}</section><section className="section-wrap soft"><span className="eyebrow green">POUR TOUS LES GOÛTS</span><h2>Explorez par activité</h2>{activities.length?<div className="activity-grid">{activities.map(activity=><Link key={activity.id} href={`/explorer?activite=${encodeURIComponent(activity.name)}`} className="activity-card"><span>{activity.icon}</span><b>{activity.name}</b></Link>)}</div>:<p>Aucune activité n’est encore configurée.</p>}</section><section className="section-wrap"><div className="split-feature"><div><span className="eyebrow green">{canOrganize?"VOTRE ESPACE ORGANISATEUR":"REJOIGNEZ LA COMMUNAUTÉ"}</span><h2>{canOrganize?"Prêt à proposer une nouvelle expérience ?":"Vous connaissez les meilleurs coins ?"}</h2><p>{canOrganize?"Créez votre prochaine sortie et retrouvez vos participants.":"Découvrez les sorties NITO ou devenez organisateur pour transmettre votre passion."}</p>{canOrganize?<Link className="primary inline" href="/organisateur/sorties/nouvelle">Proposer une sortie</Link>:user?<Link className="primary inline" href="/explorer">Explorer les sorties</Link>:<Link className="primary inline" href="/inscription?role=organisateur">Devenir organisateur</Link>}</div><div className="stats-card"><div><strong>{membersResult.count??0}</strong><span>membres</span></div><div><strong>{tripsCountResult.count??0}</strong><span>sorties publiées</span></div><div><strong>{averageRating.toFixed(1)}/5</strong><span>note moyenne</span></div><div><strong>{activities.length}</strong><span>activités</span></div></div></div></section></>;
}
