import Link from "next/link";
import type { Metadata } from "next";
import {TripCard} from "@/components/trip-card";
import {activities,trips} from "@/lib/data";
import {createClient} from "@/lib/supabase/server";
export const metadata: Metadata = {
  title: "NITO — Sorties et activités nature",
  description: "Découvrez et réservez des sorties nature guidées par des passionnés près de chez vous.",
  alternates: { canonical: "/" },
};
export default async function Home(){const supabase=await createClient();const user=supabase?(await supabase.auth.getUser()).data.user:null;const profile=user&&supabase?(await supabase.from("profiles").select("user_type").eq("id",user.id).single()).data:null;const canOrganize=profile?.user_type==="organisateur"||profile?.user_type==="administrateur";return <><section className="hero"><div className="hero-overlay"/><div className="hero-content"><span className="eyebrow">RENCONTREZ · APPRENEZ · RESPIREZ</span><h1>La nature se partage<br/>mieux ensemble.</h1><p>Découvrez des sorties guidées par des passionnés, près de chez vous.</p><form className="search-bar" action="/explorer"><label><span>Activité</span><select name="activite"><option value="">Toutes</option>{activities.map(a=><option key={a}>{a}</option>)}</select></label><label><span>Lieu</span><input name="lieu" placeholder="Votre région"/></label><label><span>Date</span><input name="date" type="date"/></label><button className="primary">Rechercher</button></form><div className="trust-line"><span>✓ Profils vérifiés</span><span>✓ Paiement sécurisé</span><span>✓ Avis authentiques</span></div></div></section><section className="section-wrap"><div className="section-title-row"><div><span className="eyebrow green">À PROXIMITÉ</span><h2>Sorties à découvrir</h2></div><Link className="text-link" href="/explorer">Voir toutes les sorties →</Link></div><div className="card-grid">{trips.map(t=><TripCard key={t.id} trip={t}/>)}</div></section><section className="section-wrap soft"><span className="eyebrow green">POUR TOUS LES GOÛTS</span><h2>Explorez par activité</h2><div className="activity-grid">{activities.map((a,i)=><Link key={a} href={`/explorer?activite=${encodeURIComponent(a)}`} className="activity-card"><span>{["🦉","🥾","🧗","📷","🌿","🔭"][i]}</span><b>{a}</b></Link>)}</div></section><section className="section-wrap"><div className="split-feature"><div><span className="eyebrow green">{canOrganize?"VOTRE ESPACE ORGANISATEUR":"REJOIGNEZ LA COMMUNAUTÉ"}</span><h2>{canOrganize?"Prêt à proposer une nouvelle expérience ?":"Vous connaissez les meilleurs coins ?"}</h2><p>{canOrganize?"Créez votre prochaine sortie et retrouvez vos participants.":"Découvrez les sorties NITO ou devenez organisateur pour transmettre votre passion."}</p>{canOrganize?<Link className="primary inline" href="/organisateur/sorties/nouvelle">Proposer une sortie</Link>:user?<Link className="primary inline" href="/explorer">Explorer les sorties</Link>:<Link className="primary inline" href="/inscription?role=organisateur">Devenir organisateur</Link>}</div><div className="stats-card"><div><strong>2 480</strong><span>membres</span></div><div><strong>312</strong><span>sorties organisées</span></div><div><strong>4,8/5</strong><span>note moyenne</span></div><div><strong>42</strong><span>activités</span></div></div></div></section></>}
