import Link from "next/link";
import {notFound} from "next/navigation";
import {DashboardNav} from "@/components/dashboard-nav";
import {TripPhotoManager} from "@/components/trip-photo-manager";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {cancelTrip,updateTrip} from "./actions";

export default async function ManageTrip({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{succes?:string;erreur?:string}>}){
  const [{id},q]=await Promise.all([params,searchParams]);const supabase=await createClient();const user=supabase?(await supabase.auth.getUser()).data.user:null;if(!user)notFound();
  const {data:trip}=await supabase!.from("trips").select("id,title,description,location,date,start_time,duration,maximum_participants,equipment,status,registrations_closed,cancellation_reason,images:trip_images(id,public_url,alt_text,position)").eq("id",id).eq("organizer_id",user.id).single();if(!trip)notFound();
  const {data:bookings}=await createAdminClient().from("bookings").select("id,number_of_people,amount,payment_status,booking_status,created_at,participant:profiles!bookings_participant_id_fkey(first_name,last_name,email)").eq("trip_id",id).order("created_at");
  const booked=(bookings??[]).filter(b=>["confirmee","terminee"].includes(b.booking_status)).reduce((s,b)=>s+b.number_of_people,0);
  const images=[...(trip.images??[])].sort((a,b)=>a.position-b.position);
  return <section className="page-shell"><DashboardNav role="organizer"/>
    <div className="page-header"><div><span className="eyebrow green">GESTION DE LA SORTIE</span><h1>{trip.title}</h1><p>{trip.status} · {booked}/{trip.maximum_participants} places confirmées</p></div><Link className="secondary" href={`/sorties/${id}`}>Voir la fiche</Link></div>
    {q.succes&&<p className="form-alert success">{q.succes==="photo"?"La photo a été ajoutée.":"Les changements ont été enregistrés et les participants prévenus."}</p>}{q.erreur&&<p className="form-alert error">{q.erreur==="limite_photos"?"La limite de huit photos est atteinte.":q.erreur==="photo"?"La photo n’a pas pu être ajoutée. Utilisez un JPG, PNG ou WebP de 10 Mo maximum.":"L’opération a échoué. Vérifiez les informations saisies."}</p>}
    <form className="big-form" action={updateTrip}><input type="hidden" name="trip_id" value={id}/><h2>Modifier les informations</h2><label>Titre<input name="title" defaultValue={trip.title} minLength={5} required/></label><label>Description<textarea name="description" defaultValue={trip.description} minLength={20} rows={5} required/></label><div className="two-cols"><label>Date<input type="date" name="date" defaultValue={trip.date} required/></label><label>Heure<input type="time" name="start_time" defaultValue={String(trip.start_time).slice(0,5)} required/></label></div><div className="two-cols"><label>Durée en minutes<input type="number" name="duration" min="30" max="1440" defaultValue={trip.duration} required/></label><label>Nombre maximal de participants<input type="number" name="maximum_participants" min={Math.max(1,booked)} max="100" defaultValue={trip.maximum_participants} required/></label></div><label>Adresse approximative<input name="location" defaultValue={trip.location} required/></label><label>Équipement<textarea name="equipment" defaultValue={trip.equipment??""} rows={3}/></label><label className="legal-consent"><input type="checkbox" name="registrations_closed" defaultChecked={trip.registrations_closed}/><span>Fermer les nouvelles inscriptions</span></label><button className="primary" disabled={trip.status==="annulee"}>Enregistrer et prévenir les participants</button></form>
    <TripPhotoManager tripId={id} images={images}/>
    <section className="panel-card"><h2>Participants</h2>{!bookings?.length?<p>Aucune réservation.</p>:bookings.map(b=>{const p=Array.isArray(b.participant)?b.participant[0]:b.participant;return <div className="admin-row" key={b.id}><span><b>{p?.first_name} {p?.last_name}</b><small>{p?.email} · {b.number_of_people} place(s)</small></span><span>{b.booking_status} · {b.payment_status} · {Number(b.amount).toFixed(2)} €</span></div>})}</section>
    {trip.status!=="annulee"&&<form className="panel-card" action={cancelTrip}><input type="hidden" name="trip_id" value={id}/><h2>Annuler la sortie</h2><p>Les participants seront prévenus. Les réservations gratuites seront simplement annulées ; les paiements confirmés seront remboursés.</p><label>Motif<textarea name="reason" minLength={5} required rows={3}/></label><button className="link-button danger">Annuler définitivement la sortie</button></form>}{trip.cancellation_reason&&<p className="secure-note">Motif d’annulation : {trip.cancellation_reason}</p>}
  </section>;
}
