"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {ChatProfile} from "@/components/messaging-client";

export type GroupChat={trip_id:string;title:string;date:string;member_role:string;last_read_at:string};
export type GroupMessage={id:string;trip_id:string;sender_id:string;content:string;created_at:string;attachment?:{id:string;original_name:string;mime_type:string}|null};
const time=(value:string)=>new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit"}).format(new Date(value));
const day=(value:string)=>new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"numeric",month:"short"}).format(new Date(value));

export function GroupMessagingClient({userId,groups,profiles,initialMessages,initialGroup}:{userId:string;groups:GroupChat[];profiles:ChatProfile[];initialMessages:GroupMessage[];initialGroup?:string}){
  const [selected,setSelected]=useState(initialGroup??groups[0]?.trip_id??"");const [messages,setMessages]=useState(initialMessages);const [readAt,setReadAt]=useState<Record<string,string>>(()=>Object.fromEntries(groups.map(group=>[group.trip_id,group.last_read_at])));const [sending,setSending]=useState(false);const [error,setError]=useState("");const end=useRef<HTMLDivElement>(null);const profileMap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);const visible=messages.filter(m=>m.trip_id===selected);const current=groups.find(g=>g.trip_id===selected);
  useEffect(()=>{const supabase=createClient();const channel=supabase.channel(`trip-groups:${userId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"trip_group_messages"},payload=>{const next=payload.new as GroupMessage;if(groups.some(g=>g.trip_id===next.trip_id))setMessages(old=>old.some(m=>m.id===next.id)?old:[...old,next])}).subscribe();return()=>{void supabase.removeChannel(channel)}},[groups,userId]);
  useEffect(()=>{if(!selected)return;void fetch("/api/messages/group",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({trip_id:selected})}).then(async response=>{if(response.ok){const data=await response.json();setReadAt(current=>({...current,[selected]:data.read_at}))}})},[selected]);
  useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[visible.length,selected]);
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();setSending(true);setError("");const form=new FormData(event.currentTarget);form.set("trip_id",selected);const response=await fetch("/api/messages/group",{method:"POST",body:form});const data=await response.json();setSending(false);if(!response.ok){setError(data.error??"Envoi impossible");return}setMessages(old=>old.some(m=>m.id===data.id)?old:[...old,data]);event.currentTarget.reset()}
  if(!groups.length)return <section className="panel-card"><h2>Groupes de sorties</h2><p>Un groupe sera créé automatiquement dès votre première réservation confirmée.</p></section>;
  return <section className="message-section"><div className="message-section-heading"><div><span className="eyebrow green">GROUPES AUTOMATIQUES</span><h2>Mes groupes de sorties</h2></div><p>L’organisateur et les participants confirmés sont ajoutés automatiquement.</p></div><div className={`messaging group-messaging ${selected?"conversation-open":""}`}><aside className="conversation-list"><div className="conversation-list-title"><h2>Groupes</h2><span>{groups.length}</span></div>{groups.map(group=>{const thread=messages.filter(m=>m.trip_id===group.trip_id);const last=thread.at(-1);const unread=thread.filter(m=>m.sender_id!==userId&&new Date(m.created_at)>new Date(readAt[group.trip_id]??0)).length;return <button className={selected===group.trip_id?"conversation active":"conversation"} key={group.trip_id} onClick={()=>setSelected(group.trip_id)}><span className="avatar">👥</span><span><span className="conversation-name"><b>{group.title}</b><time>{last?time(last.created_at):""}</time></span><small>{last?.attachment?"📎 ":""}{last?.content.slice(0,42)??"Groupe créé automatiquement"}</small></span>{unread>0&&<span className="unread-badge">{unread}</span>}</button>})}</aside><div className="chat"><div className="chat-header"><button className="mobile-chat-back" onClick={()=>setSelected("")} aria-label="Retour aux groupes">←</button><span>👥 {current?.title}<small>Organisateur et participants confirmés</small></span></div><div className="chat-messages">{!visible.length&&<p className="chat-empty">Soyez la première personne à écrire dans ce groupe.</p>}{visible.map((message,index)=>{const sender=profileMap.get(message.sender_id);const previous=visible[index-1];const showDay=!previous||new Date(previous.created_at).toDateString()!==new Date(message.created_at).toDateString();return <div key={message.id}>{showDay&&<div className="message-day"><span>{day(message.created_at)}</span></div>}<div className={message.sender_id===userId?"bubble me":"bubble"}>{message.sender_id!==userId&&<b>{sender?`${sender.first_name} ${sender.last_name}`.trim()||"Membre NITO":"Membre"}</b>}<span>{message.content}</span>{message.attachment&&<a className="attachment-link" href={`/api/messages/group-attachments/${message.attachment.id}`}>📎 {message.attachment.original_name}</a>}<small>{time(message.created_at)}</small></div></div>})}<div ref={end}/></div>{error&&<p className="form-alert error">{error}</p>}<form className="message-box" onSubmit={send}><input name="content" aria-label="Message au groupe" placeholder="Écrivez au groupe…" maxLength={4000} required/><label className="attachment-button" title="Joindre un fichier privé">📎<input type="file" name="file" accept="application/pdf,image/jpeg,image/png,image/webp"/></label><button className="primary" disabled={sending}>{sending?"Envoi…":"Envoyer"}</button></form></div></div></section>;
}
