"use client";
import { FormEvent,useEffect,useMemo,useRef,useState } from "react";
import { createClient } from "@/lib/supabase/client";

export type ChatMessage={id:number;sender_id:string;receiver_id:string;trip_id:string|null;content:string;read_at:string|null;created_at:string;attachment?:{id:string;original_name:string;mime_type:string}|null};
export type ChatProfile={id:string;first_name:string;last_name:string;avatar_url:string|null};

export function MessagingClient({userId,initialMessages,profiles,initialPeer,initialTrip}:{userId:string;initialMessages:ChatMessage[];profiles:ChatProfile[];initialPeer?:string;initialTrip?:string}){
  const [messages,setMessages]=useState(initialMessages);const [peer,setPeer]=useState(initialPeer??profiles[0]?.id??"");const trip=initialTrip??"";const [error,setError]=useState("");const [sending,setSending]=useState(false);const end=useRef<HTMLDivElement>(null);
  const profileMap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);
  const peers=useMemo(()=>Array.from(new Set(messages.flatMap(m=>[m.sender_id,m.receiver_id]).filter(id=>id!==userId).concat(initialPeer?[initialPeer]:[]))),[messages,userId,initialPeer]);
  const visible=messages.filter(m=>(m.sender_id===userId&&m.receiver_id===peer)||(m.sender_id===peer&&m.receiver_id===userId));
  useEffect(()=>{const supabase=createClient();const channel=supabase.channel(`messages:${userId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},payload=>{const next=payload.new as ChatMessage;if(next.sender_id===userId||next.receiver_id===userId)setMessages(current=>current.some(m=>m.id===next.id)?current:[...current,next]);}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"messages"},payload=>{const next=payload.new as ChatMessage;setMessages(current=>current.map(m=>m.id===next.id?{...m,...next}:m));}).subscribe();return()=>{void supabase.removeChannel(channel)}},[userId]);
  useEffect(()=>{if(!peer)return;void fetch("/api/messages",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sender_id:peer})});},[peer,userId]);
  useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[visible.length]);
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setSending(true);const form=new FormData(event.currentTarget);form.set("receiver_id",peer);form.set("trip_id",trip);const response=await fetch("/api/messages",{method:"POST",body:form});const data=await response.json();setSending(false);if(!response.ok){setError(data.error??"Envoi impossible");return}setMessages(current=>current.some(m=>m.id===data.id)?current:[...current,data]);event.currentTarget.reset();}
  async function moderate(action:"block"|"report"){if(!peer)return;const response=await fetch("/api/messages/moderation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,user_id:peer,trip_id:trip||null,reason:"comportement",details:"Signalement envoyé depuis la conversation"})});setError(response.ok?(action==="block"?"Utilisateur bloqué.":"Signalement transmis."):"Action impossible");}
  const current=profileMap.get(peer);return <div className="messaging"><aside className="conversation-list"><h2>Messages</h2>{peers.length===0?<p>Aucune conversation.</p>:peers.map(id=>{const p=profileMap.get(id);const last=[...messages].reverse().find(m=>m.sender_id===id||m.receiver_id===id);return <button className={id===peer?"conversation active":"conversation"} key={id} onClick={()=>setPeer(id)}><span className="avatar">{p?.first_name?.[0]??"?"}</span><span><b>{p?`${p.first_name} ${p.last_name}`:"Utilisateur"}</b><small>{last?.content.slice(0,35)??"Nouvelle conversation"}</small></span></button>})}</aside><div className="chat">{peer?<><div className="chat-header"><span>{current?`${current.first_name} ${current.last_name}`:"Conversation"}</span><span className="chat-actions"><button className="link-button" onClick={()=>moderate("report")}>Signaler</button><button className="link-button danger" onClick={()=>moderate("block")}>Bloquer</button></span></div><div className="chat-messages">{visible.map(m=><div className={m.sender_id===userId?"bubble me":"bubble"} key={m.id}><span>{m.content}</span>{m.attachment&&<a className="attachment-link" href={`/api/messages/attachments/${m.attachment.id}`}>📎 {m.attachment.original_name}</a>}<small>{new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit"}).format(new Date(m.created_at))}{m.sender_id===userId&&(m.read_at?" · Lu":" · Envoyé")}</small></div>)}<div ref={end}/></div>{error&&<p className={error.includes("bloqué")||error.includes("transmis")?"form-alert success":"form-alert error"}>{error}</p>}<form className="message-box" onSubmit={send}><input name="content" aria-label="Message" placeholder="Écrivez votre message…" maxLength={4000} required/><label className="attachment-button">📎<input type="file" name="file" accept="application/pdf,image/jpeg,image/png,image/webp"/></label><button className="primary" disabled={sending}>{sending?"Envoi…":"Envoyer"}</button></form></>:<div className="chat-empty">Sélectionnez une conversation.</div>}</div></div>;
}
