import Stripe from "stripe";
import {createAdminClient} from "@/lib/supabase/admin";
import {getStripe} from "@/lib/stripe/server";
import {stripeConnectState,StripeConnectSnapshot} from "@/lib/domain/stripe-connect";
import Link from "next/link";

const labels={non_commence:{title:"Configuration non commencée",tone:"neutral",text:"Préparez vos informations, puis ouvrez le formulaire sécurisé de Stripe."},informations_manquantes:{title:"Configuration à compléter",tone:"warning",text:"Votre compte existe, mais le formulaire Stripe n’est pas terminé."},verification_en_cours:{title:"Vérification Stripe en cours",tone:"warning",text:"Stripe vérifie les informations transmises. Une nouvelle demande peut apparaître ultérieurement."},action_requise:{title:"Action requise par Stripe",tone:"danger",text:"Des informations ou justificatifs supplémentaires sont nécessaires pour activer le compte."},active:{title:"Paiements et versements activés",tone:"success",text:"Votre compte connecté est prêt à recevoir des paiements et des versements."}} as const;
function snapshot(account:Stripe.Account):StripeConnectSnapshot{return {chargesEnabled:Boolean(account.charges_enabled),payoutsEnabled:Boolean(account.payouts_enabled),detailsSubmitted:Boolean(account.details_submitted),currentlyDue:account.requirements?.currently_due??[],eventuallyDue:account.requirements?.eventually_due??[],disabledReason:account.requirements?.disabled_reason??null,currentDeadline:account.requirements?.current_deadline??null}}

export async function StripeOnboardingCard({userId,queryStatus}:{userId:string;queryStatus?:string}){
  const {data:organizer}=await createAdminClient().from("organizer_profiles").select("stripe_connect_account_id").eq("organizer_id",userId).maybeSingle();let live:StripeConnectSnapshot|null=null;let unavailable=false;
  if(organizer?.stripe_connect_account_id){try{live=snapshot(await getStripe().accounts.retrieve(organizer.stripe_connect_account_id) as Stripe.Account)}catch{unavailable=true}}
  const state=stripeConnectState(live);const label=labels[state];
  return <section className="panel-card connect-card stripe-assistant"><span className="eyebrow green">VERSEMENTS SÉCURISÉS</span><h2>Compte Stripe Connect</h2>
    {queryStatus==="plateforme-incomplete"&&<p className="form-alert error">La configuration Connect de NITO doit être finalisée avant de créer ce compte.</p>}{queryStatus==="erreur"&&<p className="form-alert error">Stripe n’a pas pu ouvrir la configuration. Réessayez ou contactez le support.</p>}{unavailable&&<p className="form-alert error">Le statut Stripe est momentanément indisponible. Vos données restent enregistrées.</p>}
    <div className={`stripe-status stripe-status-${label.tone}`}><span className="stripe-status-dot"/><div><strong>{label.title}</strong><p>{label.text}</p></div></div>
    <div className="stripe-capabilities" aria-label="État des fonctionnalités Stripe"><div><span>{live?.detailsSubmitted?"✓":"1"}</span><strong>Informations</strong><small>{live?.detailsSubmitted?"Transmises":"À compléter"}</small></div><div><span>{live?.chargesEnabled?"✓":"2"}</span><strong>Paiements</strong><small>{live?.chargesEnabled?"Activés":"Non activés"}</small></div><div><span>{live?.payoutsEnabled?"✓":"3"}</span><strong>Versements</strong><small>{live?.payoutsEnabled?"Activés":"Non activés"}</small></div></div>
    {live?.currentlyDue.length?<div className="stripe-requirements"><strong>{live.currentlyDue.length} élément(s) demandé(s) par Stripe</strong><p>Ouvrez la configuration pour connaître les informations ou justificatifs attendus. NITO ne reçoit pas vos documents bancaires ou d’identité.</p>{live.currentDeadline&&<small>Échéance Stripe : {new Intl.DateTimeFormat("fr-FR",{dateStyle:"long"}).format(new Date(live.currentDeadline*1000))}</small>}</div>:null}
    <details className="stripe-guide" open={!live}><summary>Ce qu’il faut préparer</summary><ul><li>Pièce d’identité et numéro de téléphone</li><li>Adresse personnelle et IBAN</li><li>SIREN/SIRET pour une activité rémunérée</li><li>Description de votre activité et adresse de votre site</li></ul><p><strong>Statut :</strong> un particulier peut proposer des sorties gratuites. Une sortie payante nécessite une structure permettant de déclarer les revenus : micro-entreprise, entreprise, société ou association.</p><p><strong>Secteur conseillé :</strong> Divertissement et loisirs → Loisirs et activités récréatives.</p></details>
    <p className="secure-note">Stripe vérifie directement votre identité et votre compte bancaire. NITO ne conserve ni votre pièce d’identité ni votre IBAN.</p>
    <div className="stripe-actions">{state==="active"?<form action="/api/connect/dashboard" method="post"><button className="primary">Gérer mon compte Stripe</button></form>:<form action="/api/create-connect-account" method="post"><button className="primary">{organizer?.stripe_connect_account_id?"Reprendre ma configuration":"Configurer mes versements"}</button></form>}{organizer?.stripe_connect_account_id&&state!=="active"?<form action="/api/connect/dashboard" method="post"><button className="secondary">Ouvrir Stripe Express</button></form>:null}<Link className="secondary" href="/aide/stripe-organisateurs">Consulter le guide Stripe</Link><a className="secondary" href="mailto:support@nito-nature.fr?subject=Aide%20Stripe%20Connect">Contacter le support</a></div>
  </section>
}
