import Link from "next/link";
import {LegalDraftWarning} from "@/components/legal-draft-warning";

export const metadata={title:"Conditions générales"};

export default function Terms(){return <section className="page-shell narrow legal-page"><span className="eyebrow green">CONDITIONS GÉNÉRALES</span><h1>Utilisation et réservation</h1><p className="legal-version">Version du 16 août 2026.</p><LegalDraftWarning/>
<h2>1. Rôle de NITO et contrat de sortie</h2><p>NITO fournit un service de mise en relation, de réservation et de paiement entre participants et organisateurs de sorties nature. Sauf mention expresse contraire sur l’annonce, le contrat portant sur la sortie est conclu directement entre le participant et l’organisateur identifié dans le récapitulatif de réservation. NITO est l’intermédiaire technique et commercial et n’est pas l’organisateur de la sortie. L’organisateur demeure responsable de la description, du statut sous lequel il agit, de l’encadrement, de la sécurité et de l’exécution de sa sortie. Stripe traite les paiements et versements.</p>
<h2>2. Comptes et majorité</h2><p>L’utilisateur fournit des informations exactes et protège ses identifiants. La réservation est réservée aux personnes majeures capables de contracter. Un adulte reste responsable des mineurs qu’il inscrit.</p>
<h2>3. Organisateurs particuliers et professionnels</h2><p>Chaque organisateur doit déclarer son statut réel. Un professionnel doit afficher les informations légales, assurances, qualifications et garanties exigées pour son activité. Un particulier ne doit pas présenter une activité habituelle comme occasionnelle ni se prévaloir de qualifications qu’il ne possède pas.</p>
<h2>4. Activités sportives et qualifications</h2><p>Une rencontre gratuite, une expérience payante de découverte et un encadrement sportif rémunéré constituent des cadres différents. L’organisateur doit choisir le cadre correspondant réellement à sa prestation. Tout enseignement, animation, encadrement ou entraînement sportif contre rémunération doit respecter les obligations de qualification et de déclaration applicables à l’activité. NITO peut exiger un diplôme, une carte professionnelle en cours de validité, une assurance adaptée et une preuve d’affiliation. Consultez la page <Link href="/securite-sportive">Sécurité et encadrement sportif</Link>.</p>
<h2>5. Publication et modération</h2><p>Les annonces sont contrôlées avant publication. NITO peut refuser, suspendre ou déréférencer une annonce incomplète, trompeuse, dangereuse, illicite ou contraire aux présentes conditions. Les règles détaillées figurent dans la rubrique <Link href="/transparence">Classement et transparence</Link>.</p>
<h2>6. Prix, commission, paiement et facturation</h2><p>Le prix total est affiché en euros avant paiement. Pour le MVP, NITO retient une commission de 10 % sur le montant de la réservation ; elle est comprise dans le prix affiché et déduite de la somme reversée à l’organisateur. Aucun paiement ne doit être effectué en dehors du parcours Stripe de NITO. L’organisateur, prestataire de la sortie, est responsable de la facture ou note due au participant lorsque la réglementation l’exige. NITO remet un justificatif de réservation et facture sa commission à l’organisateur selon le cadre fiscal applicable. Le justificatif NITO ne remplace pas la facture du prestataire.</p>
<h2>7. Annulation et remboursement</h2><p>Les règles applicables sont présentées dans la <Link href="/annulations">politique d’annulation</Link> et doivent être acceptées avant le paiement. Les activités de loisirs fournies à une date déterminée peuvent être exclues du droit de rétractation de quatorze jours.</p>
<h2>8. Sécurité et comportement</h2><p>Chaque participant respecte les consignes, le milieu naturel et les autres utilisateurs. Sont interdits : fraude, harcèlement, discrimination, contenu illicite, usurpation d’identité, contournement des règles et mise en danger d’autrui.</p>
<h2>9. Avis</h2><p>Seuls les participants disposant d’une réservation terminée peuvent publier un avis. Les avis ne sont pas rémunérés et peuvent être retirés s’ils sont illicites, injurieux, frauduleux ou sans rapport avec la sortie.</p>
<h2>10. Responsabilité</h2><p>NITO répond de son service d’intermédiation dans les limites prévues par la loi. NITO ne garantit ni les conditions météorologiques ni l’absence de risque inhérente aux activités de plein air. Aucune clause ne limite les droits impératifs des consommateurs.</p>
<h2>11. Suspension et fermeture</h2><p>Un compte peut être suspendu en cas de risque de sécurité, fraude ou violation grave. Sauf urgence ou obligation légale, l’utilisateur est informé du motif et peut présenter ses observations.</p>
<h2>12. Réclamations et droit applicable</h2><p>Le droit français s’applique. L’utilisateur doit d’abord contacter NITO. Les voies de recours figurent sur la page <Link href="/signalement-litiges">Signalements et litiges</Link>.</p></section>}
