import Link from "next/link";
import {redirect} from "next/navigation";
import {DashboardNav} from "@/components/dashboard-nav";
import {createClient} from "@/lib/supabase/server";

export const metadata={title:"Mes réservations"};
export default async function Reservations({searchParams}:{searchParams:Promise<{remboursement?:string}>}){
  const q=await searchParams;const supabase=await createClient();const user=supabase?(await supabase.auth.getUser()).data.user:null;if(!user)redirect("/connexion?next=/reservations");
  const {data:bookings}=await supabase!.from("bookings").select("id,number_of_people,amount,platform_fee,payment_status,booking_status,created_at,cancellation_reason,trip:trips(id,title,date,start_time,location,status)").eq("participant_id",user.id).order("created_at",{ascending:false});
  return <section className="page-shell"><DashboardNav role="participant"/><span className="eyebrow green">MON COMPTE</span><h1>Mes réservations</h1>{q.remboursement&&<p className="form-alert success">Votre annulation a été enregistrée et le remboursement demandé.</p>}{!bookings?.length?<div className="empty-state"><h2>Aucune réservation</h2><Link className="primary" href="/explorer">Découvrir les sorties</Link></div>:<div className="calendar-list">{bookings.map(b=>{const trip=Array.isArray(b.trip)?b.trip[0]:b.trip;return <article className="panel-card" key={b.id}><div className="page-header"><div><h2>{trip?.title??"Sortie indisponible"}</h2><p>{trip&&new Intl.DateTimeFormat("fr-FR",{dateStyle:"long"}).format(new Date(trip.date))} {trip&&`à ${String(trip.start_time).slice(0,5)} · ${trip.location}`}</p><p>{b.number_of_people} place(s) · {Number(b.amount).toFixed(2)} € · {b.booking_status} · {b.payment_status}</p></div>{trip&&<Link className="secondary" href={`/sorties/${trip.id}`}>Voir la sortie</Link>}</div><div className="form-actions"><Link className="text-link" href={`/api/bookings/${b.id}/receipt`} target="_blank">Télécharger le justificatif</Link>{b.booking_status==="confirmee"&&<form action="/api/refund-booking" method="post"><input type="hidden" name="bookingId" value={b.id}/><input type="hidden" name="returnTo" value="/reservations"/><input type="hidden" name="reason" value="Annulation demandée par le participant"/><button className="link-button danger">Annuler et demander le remboursement</button></form>}</div>{b.cancellation_reason&&<small>Motif : {b.cancellation_reason}</small>}</article>})}</div>}</section>;
}
