import Link from "next/link";
export const metadata={title:"Politique relative aux cookies"};
export default function Cookies(){return <section className="page-shell narrow legal-page"><span className="eyebrow green">TRACEURS</span><h1>Politique relative aux cookies</h1><p className="legal-version">Version du 4 août 2026.</p>
<h2>Cookies actuellement utilisés</h2><p>NITO utilise uniquement les cookies et mécanismes de stockage strictement nécessaires à l’authentification Supabase, à la sécurité, au maintien de session et au fonctionnement du paiement. Ils ne servent pas à établir un profil publicitaire.</p>
<h2>Mesure d’audience</h2><p>NITO utilise Vercel Web Analytics pour obtenir des statistiques agrégées sur les pages publiques. Cet outil ne dépose pas de cookie, ne suit pas une personne entre plusieurs jours ou plusieurs sites et ne reçoit ni les pages privées du compte, ni les paramètres d’URL, ni les identifiants présents dans les adresses publiques.</p>
<h2>Consentement</h2><p>Les mécanismes strictement nécessaires et cette mesure d’audience limitée, anonyme et sans publicité ne nécessitent pas de bandeau lorsque les conditions d’exemption applicables sont respectées. NITO réévalue cette configuration en cas d’évolution de l’outil ou des finalités.</p>
<h2>Évolution</h2><p>Avant l’ajout d’un outil non essentiel, NITO mettra en place un choix permettant d’accepter ou refuser avec la même facilité, conservera la preuve du choix et permettra son retrait à tout moment.</p>
<h2>Gestion dans le navigateur</h2><p>Vous pouvez supprimer ou bloquer les cookies dans votre navigateur. Le blocage des cookies nécessaires peut empêcher la connexion, la réservation ou le paiement.</p>
<p>Pour en savoir plus, consultez la <Link href="/confidentialite">politique de confidentialité</Link>.</p></section>}
