import Link from "next/link";

export const metadata={title:"Sécurité et encadrement sportif"};

export default function SportsSafety(){return <section className="page-shell narrow legal-page"><span className="eyebrow green">SÉCURITÉ DES ACTIVITÉS</span><h1>Rencontre, expérience ou encadrement sportif</h1><p className="legal-version">Information générale — mise à jour du 6 août 2026.</p>
<h2>Trois cadres différents</h2><p><strong>Une rencontre gratuite entre particuliers</strong> permet de partager une pratique sans rémunération et sans se présenter comme encadrant professionnel. <strong>Une expérience payante animée par un passionné</strong> peut porter sur la découverte de la nature ou le partage de connaissances, mais ne doit pas masquer un enseignement ou un encadrement sportif réglementé. <strong>Un encadrement sportif rémunéré</strong> consiste à enseigner, animer, encadrer ou entraîner une activité physique ou sportive contre rémunération.</p>
<h2>Qualification obligatoire</h2><p>Lorsqu’une sortie constitue un encadrement sportif rémunéré, NITO exige un statut professionnel compatible, une qualification autorisant l’activité concernée et une assurance vérifiées. La carte professionnelle est également demandée lorsqu’elle est requise. Certaines disciplines et certains milieux, notamment l’escalade en milieu naturel ou le canoë-kayak sur certaines rivières, répondent à des conditions particulières.</p>
<h2>Niveaux d’organisateurs</h2><ul><li>Passionné vérifié</li><li>Association</li><li>Professionnel diplômé</li><li>Guide ou éducateur sportif</li></ul>
<h2>Justificatifs</h2><p>Selon le statut et l’activité, NITO peut demander une assurance de responsabilité civile professionnelle, un diplôme ou titre reconnu, une carte professionnelle en cours de validité et un justificatif d’affiliation à une structure. Le périmètre et les exclusions du contrat d’assurance doivent correspondre à l’activité réellement proposée.</p>
<h2>Contrôle avant publication</h2><p>Une annonce présentant un encadrement sportif rémunéré ne peut pas être créée tant que la qualification et l’assurance n’ont pas été validées. NITO peut demander des justificatifs complémentaires, refuser une annonce ou la suspendre si le cadre déclaré ne correspond pas à la prestation.</p>
<p>Cette page fournit une information générale et ne remplace pas l’examen du diplôme, de ses prérogatives, de la carte professionnelle, du contrat d’assurance et des règles propres à chaque activité. Consultez aussi les <Link href="/conditions">conditions générales</Link>.</p></section>}
