import {redirect} from "next/navigation";
import {DashboardNav} from "@/components/dashboard-nav";
import {MessagingClient,ChatMessage,ChatProfile} from "@/components/messaging-client";
import {GroupMessagingClient,GroupChat,GroupMessage} from "@/components/group-messaging-client";
import {createClient} from "@/lib/supabase/server";
export const metadata={title:"Messagerie"};
export default async function Messages({searchParams}:{searchParams:Promise<{with?:string;trip?:string;group?:string}>}){
  const q=await searchParams;const supabase=await createClient();if(!supabase)redirect("/connexion");const user=(await supabase.auth.getUser()).data.user;if(!user)redirect("/connexion");
  const {data:viewer}=await supabase.from("profiles").select("user_type").eq("id",user.id).single();
  const [{data:raw},{data:memberships}]=await Promise.all([supabase.from("messages").select("id,sender_id,receiver_id,trip_id,content,read_at,created_at,message_attachments(id,original_name,mime_type)").or(`sender_id.eq.${user.id},receiver_id.eq.${user.id}`).order("created_at",{ascending:true}).limit(500),supabase.from("trip_group_members").select("trip_id,member_role,last_read_at,trip:trips(title,date)").eq("user_id",user.id).is("left_at",null)]);
  const messages=(raw??[]).map(m=>({...m,attachment:m.message_attachments?.[0]??null})) as ChatMessage[];const tripIds=(memberships??[]).map(m=>m.trip_id);const {data:groupRaw}=tripIds.length?await supabase.from("trip_group_messages").select("id,trip_id,sender_id,content,created_at,trip_group_message_attachments(id,original_name,mime_type)").in("trip_id",tripIds).order("created_at",{ascending:true}).limit(1000):{data:[]};const groupMessages=(groupRaw??[]).map(message=>({...message,attachment:message.trip_group_message_attachments?.[0]??null})) as GroupMessage[];
  const ids=Array.from(new Set(messages.flatMap(m=>[m.sender_id,m.receiver_id]).concat(groupMessages.map(m=>m.sender_id),q.with?[q.with]:[]))).filter(id=>id!==user.id);const {data:profiles}=ids.length?await supabase.from("profiles").select("id,first_name,last_name,avatar_url").in("id",ids):{data:[]};const chatProfiles=(profiles??[]) as ChatProfile[];
  const groups=(memberships??[]).map(m=>{const trip=Array.isArray(m.trip)?m.trip[0]:m.trip;return {trip_id:m.trip_id,title:trip?.title??"Groupe de sortie",date:trip?.date??"",member_role:m.member_role,last_read_at:m.last_read_at} as GroupChat});
  return <section className="page-shell messages-page"><DashboardNav role={viewer?.user_type??"participant"}/><div className="messages-page-title"><div><span className="eyebrow green">VOS ÉCHANGES</span><h1>Messagerie</h1></div><p>Messages en temps réel, groupes de sorties et fichiers privés.</p></div><GroupMessagingClient userId={user.id} groups={groups} profiles={chatProfiles} initialMessages={groupMessages} initialGroup={q.group??q.trip}/><section className="message-section private-message-section"><div className="message-section-heading"><div><span className="eyebrow green">ÉCHANGES DIRECTS</span><h2>Messages privés</h2></div><p>Les pièces jointes sont protégées par un lien temporaire.</p></div><MessagingClient userId={user.id} initialMessages={messages} profiles={chatProfiles} initialPeer={q.with} initialTrip={q.trip}/></section></section>;
}
