export const metadata={title:"Classement et transparence"};
export default function Transparency(){return <section className="page-shell narrow legal-page"><span className="eyebrow green">TRANSPARENCE DE LA PLATEFORME</span><h1>Référencement, classement et commissions</h1><p className="legal-version">Version du 16 août 2026.</p>
<h2>Qui peut proposer une sortie ?</h2><p>Les organisateurs peuvent être des particuliers, associations ou professionnels. Leur statut déclaré apparaît sur leur profil et leur annonce. Un particulier peut proposer une rencontre gratuite et occasionnelle, sans se présenter comme professionnel. Une association agit dans le cadre de son objet, de ses responsables et de ses assurances. Un professionnel doit communiquer son identité juridique, son numéro d’immatriculation lorsqu’il est requis, ses assurances, ses qualifications et les garanties imposées par son activité. Une sortie payante n’est publiée que si l’organisateur dispose d’un statut permettant de déclarer les sommes reçues.</p>
<h2>Niveaux et encadrement sportif</h2><p>NITO distingue les passionnés vérifiés, les associations, les professionnels diplômés et les guides ou éducateurs sportifs. Une annonce qualifiée d’encadrement sportif rémunéré est conditionnée à la vérification d’une qualification adaptée et d’une assurance. Le niveau affiché n’étend jamais les prérogatives du diplôme ni la couverture du contrat d’assurance.</p>
<h2>Référencement</h2><p>Une sortie est référencée après création d’un compte organisateur, transmission des informations demandées et validation administrative. Une annonce peut être refusée ou retirée si elle est incomplète, trompeuse, illicite, dangereuse, expirée ou contraire aux conditions NITO.</p>
<h2>Classement par défaut</h2><p>Dans le MVP, les résultats sont principalement filtrés par activité, lieu et date demandés. À critères égaux, les sorties les plus proches dans le temps sont destinées à apparaître en priorité. La note peut être affichée mais n’entraîne pas de placement payant.</p>
<h2>Référencement payant</h2><p>NITO ne propose actuellement aucun classement sponsorisé. Si une mise en avant payante est introduite, elle sera signalée par la mention « Annonce » et son influence sur le classement sera expliquée ici.</p>
<h2>Prix et commission</h2><p>Le référencement est gratuit. NITO prélève une commission de 10 % sur chaque réservation payante. Exemple : pour une réservation de 30 €, NITO conserve 3 € et 27 € sont destinés à l’organisateur, sous réserve des remboursements, litiges et frais applicables. Le prix affiché au participant inclut cette commission.</p>
<h2>Actualisation</h2><p>Les disponibilités et statuts sont actualisés depuis la base de données. L’organisateur reste responsable de la mise à jour des caractéristiques et de l’annulation rapide d’une sortie qui ne peut plus être assurée.</p></section>}
