import Link from "next/link";
import {DashboardNav} from "@/components/dashboard-nav";
import {createAdminClient} from "@/lib/supabase/admin";

export const metadata={title:"Administration NITO"};

export default async function Admin(){
  const admin=createAdminClient();const [{count:users},{count:active},{count:bookings},{count:reports},{count:documents},{count:disputes},{count:reviews},{count:pendingTrips},{count:pendingRefunds},{count:suspended},{count:failedPayments},{count:unprocessedEvents},{data:latestLogs}]=await Promise.all([
    admin.from("profiles").select("id",{count:"exact",head:true}),admin.from("trips").select("id",{count:"exact",head:true}).eq("status","publiee"),admin.from("bookings").select("id",{count:"exact",head:true}),admin.from("reports").select("id",{count:"exact",head:true}).in("status",["ouvert","en_cours"]),admin.from("organizer_documents").select("id",{count:"exact",head:true}).eq("status","en_attente"),admin.from("payment_disputes").select("id",{count:"exact",head:true}).not("status","in",'(won,lost,warning_closed)'),admin.from("reviews").select("id",{count:"exact",head:true}),admin.from("trips").select("id",{count:"exact",head:true}).eq("status","en_attente"),admin.from("refunds").select("id",{count:"exact",head:true}).in("status",["en_attente","rembourse_partiel"]),admin.from("profiles").select("id",{count:"exact",head:true}).eq("account_status","suspendu"),admin.from("bookings").select("id",{count:"exact",head:true}).eq("payment_status","echoue"),admin.from("stripe_events").select("stripe_event_id",{count:"exact",head:true}).is("processed_at",null),admin.from("admin_audit_logs").select("id,action,entity_type,created_at").order("created_at",{ascending:false}).limit(5),
  ]);
  const attention=[{icon:"🕒",title:"Éléments en attente",value:(pendingTrips??0)+(documents??0),description:`${pendingTrips??0} sortie(s) et ${documents??0} document(s) à contrôler.`,href:"/administration/sorties"},{icon:"🚩",title:"Signalements",value:reports??0,description:"Signalements ouverts ou en cours de traitement.",href:"/administration/signalements"},{icon:"↩️",title:"Remboursements",value:pendingRefunds??0,description:"Demandes et remboursements à suivre.",href:"/administration/reservations"},{icon:"⛔",title:"Comptes suspendus",value:suspended??0,description:"Comptes suspendus et décisions de réactivation.",href:"/administration/utilisateurs"},{icon:"⚠️",title:"Incidents de paiement",value:(disputes??0)+(failedPayments??0)+(unprocessedEvents??0),description:`${disputes??0} litige(s), ${failedPayments??0} échec(s), ${unprocessedEvents??0} webhook(s) à vérifier.`,href:"/administration/finances"},{icon:"📋",title:"Journal des actions",value:latestLogs?.length??0,description:"Dernières décisions administratives tracées.",href:"/administration/journal"}];
  const secondary=[{title:"Avis",description:`${reviews??0} avis publié(s) à superviser.`,href:"/administration/avis"},{title:"E-mails",description:"Contrôler les envois transactionnels.",href:"/administration/emails"},{title:"Procédures",description:"Support, modération, litiges et urgences.",href:"/administration/procedures"},{title:"Justificatifs",description:"Examiner qualifications et assurances.",href:"/administration/documents"}];
  const urgent=attention.reduce((sum,item)=>sum+Number(item.value),0);
  return <section className="page-shell role-dashboard"><DashboardNav role="administrateur"/><div className="page-header"><div><span className="eyebrow green">ADMINISTRATION NITO</span><h1>Centre de contrôle</h1><p>Les priorités opérationnelles sont regroupées ici sans retirer les outils existants.</p></div></div>{urgent>0&&<div className="dashboard-alert danger"><b>⚠️ {urgent} élément{urgent!==1&&"s"} requiert{urgent===1?"":"èrent"} votre attention</b><span>Traitez d’abord les incidents et signalements.</span></div>}<div className="role-action-grid admin-attention-grid">{attention.map(item=><Link className={`role-action-card ${item.value?"needs-attention":""}`} href={item.href} key={item.title}><span className="role-action-icon">{item.icon}</span><div><span>{item.title}</span><strong>{item.value}</strong><p>{item.description}</p><b>Ouvrir →</b></div></Link>)}</div><div className="admin-kpis"><div><span>Utilisateurs</span><strong>{users??0}</strong></div><div><span>Sorties actives</span><strong>{active??0}</strong></div><div><span>Réservations</span><strong>{bookings??0}</strong></div><div><span>Documents à contrôler</span><strong>{documents??0}</strong></div></div><div className="dashboard-two-columns"><section className="panel-card"><div className="section-heading-compact"><h2>Dernières actions</h2><Link className="text-link" href="/administration/journal">Journal complet</Link></div>{!latestLogs?.length?<p>Aucune action enregistrée.</p>:latestLogs.map(log=><p className="audit-preview" key={log.id}><b>{log.action}</b><small>{log.entity_type} · {new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(log.created_at))}</small></p>)}</section><section className="panel-card"><h2>Autres outils</h2>{secondary.map(item=><Link className="admin-tool-link" href={item.href} key={item.href}><b>{item.title}</b><span>{item.description}</span></Link>)}</section></div></section>;
}
