import Link from "next/link";
import {redirect,notFound} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";

const levelLabels:Record<string,string>={passionne_verifie:"Passionné vérifié",association:"Association",professionnel_diplome:"Professionnel diplômé",guide_educateur_sportif:"Guide ou éducateur sportif"};

export default async function BookingSummary({searchParams}:{searchParams:Promise<{tripId?:string;quantity?:string;booking_terms?:string}>}){
  const q=await searchParams;const tripId=String(q.tripId??"");const quantity=Number(q.quantity??1);
  if(!/^[0-9a-f-]{36}$/i.test(tripId)||!Number.isInteger(quantity)||quantity<1||quantity>20)notFound();
  if(q.booking_terms!=="accepted")redirect(`/sorties/${tripId}?reservation=conditions`);
  const supabase=await createClient();const user=supabase?(await supabase.auth.getUser()).data.user:null;if(!user)redirect(`/connexion?next=/reservation/recapitulatif?tripId=${tripId}&quantity=${quantity}&booking_terms=accepted`);
  const admin=createAdminClient();
  const [{data:trip},{data:bookings}]=await Promise.all([
    admin.from("trips").select("id,title,date,start_time,location,price,maximum_participants,status,registrations_closed,organizer_id,organizer:profiles!trips_organizer_id_fkey(first_name,last_name,identity_verified),activity:activities(name)").eq("id",tripId).single(),
    admin.from("bookings").select("number_of_people").eq("trip_id",tripId).in("booking_status",["confirmee","terminee"]),
  ]);
  if(!trip)notFound();const booked=(bookings??[]).reduce((sum,item)=>sum+item.number_of_people,0);if(trip.status!=="publiee"||trip.registrations_closed||quantity>trip.maximum_participants-booked)redirect(`/sorties/${tripId}?reservation=impossible`);
  const organizer=Array.isArray(trip.organizer)?trip.organizer[0]:trip.organizer;const activity=Array.isArray(trip.activity)?trip.activity[0]:trip.activity;const {data:organizerDetails}=await admin.from("organizer_profiles").select("organizer_level,affiliation_name,qualification_verified,insurance_verified").eq("organizer_id",trip.organizer_id).maybeSingle();
  const unitPrice=Number(trip.price);const total=unitPrice*quantity;const fee=Math.round(total*10)/100;const organizerName=`${organizer?.first_name??""} ${organizer?.last_name??""}`.trim()||"Organisateur NITO";const action=total>0?"/api/create-checkout-session":"/api/bookings/free";
  return <section className="page-shell booking-summary-page"><div className="summary-heading"><span className="eyebrow green">DERNIÈRE ÉTAPE AVANT CONFIRMATION</span><h1>Récapitulatif de votre réservation</h1><p>Vérifiez attentivement les informations avant de continuer.</p></div><div className="booking-summary-grid"><section className="panel-card"><h2>{trip.title}</h2><dl className="summary-list"><div><dt>Activité</dt><dd>{activity?.name??"Sortie nature"}</dd></div><div><dt>Date et horaire</dt><dd>{new Intl.DateTimeFormat("fr-FR",{dateStyle:"long"}).format(new Date(trip.date))} à {String(trip.start_time).slice(0,5)}</dd></div><div><dt>Lieu approximatif</dt><dd>{trip.location}<small>Le rendez-vous exact est communiqué après confirmation.</small></dd></div><div><dt>Prestataire</dt><dd>{organizerName}<small>{organizerDetails?.affiliation_name||levelLabels[organizerDetails?.organizer_level??""]||"Organisateur NITO"}</small></dd></div></dl><div className="verification-badges">{organizer?.identity_verified&&<span>✓ Identité vérifiée</span>}{organizerDetails?.qualification_verified&&<span>✓ Qualification vérifiée</span>}{organizerDetails?.insurance_verified&&<span>✓ Assurance vérifiée</span>}</div><div className="cancellation-box"><h3>Conditions d’annulation</h3><p>L’annulation se gère depuis « Mes réservations ». Le remboursement éventuel dépend du délai et des circonstances prévues par la politique NITO.</p><Link className="text-link" href="/annulations" target="_blank">Lire la politique complète</Link></div></section><aside className="panel-card price-summary"><h2>Total</h2><div className="price-line"><span>{quantity} participant{quantity>1&&"s"} × {unitPrice.toFixed(2)} €</span><strong>{total.toFixed(2)} €</strong></div><div className="price-line muted"><span>Commission NITO incluse (10 %)</span><span>{fee.toFixed(2)} €</span></div><div className="price-total"><span>À payer</span><strong>{total===0?"Gratuit":`${total.toFixed(2)} €`}</strong></div><form action={action} method="post"><input type="hidden" name="tripId" value={trip.id}/><input type="hidden" name="quantity" value={quantity}/><input type="hidden" name="booking_terms" value="accepted"/><button className="primary wide">{total>0?`Payer ${total.toFixed(2)} € avec Stripe`:"Confirmer la réservation gratuite"}</button></form><Link className="secondary wide summary-back" href={`/sorties/${trip.id}`}>Modifier ma sélection</Link><small className="payment-disclaimer">Aucun débit n’est effectué avant la validation finale chez Stripe.</small></aside></div></section>;
}
