import Link from "next/link";
import {LegalDraftWarning} from "@/components/legal-draft-warning";
export const metadata={title:"Politique de confidentialité"};
export default function Privacy(){return <section className="page-shell narrow legal-page"><span className="eyebrow green">DONNÉES PERSONNELLES</span><h1>Politique de confidentialité</h1><p className="legal-version">Version du 4 août 2026.</p><LegalDraftWarning/>
<h2>Responsable du traitement</h2><p>NITO est responsable des traitements décrits ci-dessous. Contact : <a href="mailto:support@nito-nature.fr">support@nito-nature.fr</a>.</p>
<h2>Données, finalités et durées</h2><div className="legal-table-wrap"><table className="legal-table"><thead><tr><th>Données</th><th>Usage et base légale</th><th>Durée indicative</th></tr></thead><tbody><tr><td>Compte et profil</td><td>Créer et sécuriser le compte — contrat</td><td>Compte actif, puis suppression ou archivage légal</td></tr><tr><td>Réservations et paiements</td><td>Exécuter, facturer et rembourser — contrat et obligations légales</td><td>10 ans pour les pièces comptables</td></tr><tr><td>Messages et signalements</td><td>Communication, sécurité et litiges — contrat et intérêt légitime</td><td>Compte actif, puis archivage nécessaire au litige, au plus 5 ans</td></tr><tr><td>Position et rendez-vous</td><td>Présenter et organiser la sortie — contrat</td><td>Durée de la sortie puis archivage limité</td></tr><tr><td>Documents organisateur</td><td>Vérifier les conditions d’activité — obligation légale et intérêt légitime</td><td>Durée de validité puis suppression, sauf litige</td></tr><tr><td>Audience des pages publiques</td><td>Statistiques agrégées sans cookie ni identifiant durable — intérêt légitime</td><td>Données agrégées selon la durée configurée chez Vercel</td></tr><tr><td>Journaux techniques</td><td>Sécurité et prévention des abus — intérêt légitime</td><td>12 mois maximum, sauf incident</td></tr></tbody></table></div>
<h2>Destinataires et sous-traitants</h2><p>Les données sont accessibles aux personnes habilitées de NITO et, selon le service, à Supabase, Vercel, Stripe et au fournisseur cartographique. Le point de rendez-vous exact n’est communiqué qu’aux personnes autorisées après réservation.</p>
<h2>Transferts hors Espace économique européen</h2><p>Certains prestataires peuvent traiter des données hors EEE. NITO doit vérifier et documenter les garanties applicables, telles qu’une décision d’adéquation ou les clauses contractuelles types.</p>
<h2>Vos droits</h2><p>Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, l’opposition et, lorsque applicable, la portabilité. Vous pouvez retirer un consentement et introduire une réclamation auprès de la CNIL. Une réponse sera apportée en principe sous un mois.</p>
<h2>Suppression du compte</h2><p>Une demande peut être envoyée via la <Link href="/contact">page Contact</Link>. Les données nécessaires aux obligations comptables, à la prévention de la fraude ou à un contentieux peuvent être archivées pendant la durée légale applicable.</p>
<h2>Sécurité</h2><p>NITO applique des contrôles d’accès par rôle, les politiques Supabase RLS, des espaces privés pour les documents, des liens temporaires et des routes serveur pour les clés secrètes. Les pièces d’identité et selfies sont traités par Stripe Identity et ne sont pas copiés dans la base NITO.</p>
<h2>Cookies</h2><p>Consultez la <Link href="/cookies">politique relative aux cookies</Link>.</p></section>}
